version: "2"

services:
  welcomepage:
    build: welcomepage

  adminpage:
    build: adminpage

  jenkins:
    image: jenkins
    #environment:
    #  - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"

  applauncher:
    build: AppLauncher
    environment:
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_USER=${JENKINS_USER}
      - JENKINS_PASSWORD=${JENKINS_PASSWORD}
      - ARTIFACTORY_URL=${ARTIFACTORY_URL}
      - ARTIFACTORY_USER=${ARTIFACTORY_USER}
      - ARTIFACTORY_PASSWORD=${ARTIFACTORY_PASSWORD}
      - DOCKER_HUB_USER=${DOCKER_HUB_USER}
      - DOCKER_HUB_PASSWORD=${DOCKER_HUB_PASSWORD}

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    volumes:
      - artifactory-data:/var/opt/jfrog/artifactory/data 
      - artifactory-logs:/var/opt/jfrog/artifactory/logs 
      - artifactory-etc:/var/opt/jfrog/artifactory/etc 

  nginx-proxy:
    build: nginx-proxy
    ports:
      - "443:443"
    depends_on:
      - jenkins
      - applauncher
      - welcomepage
      - adminpage

volumes:
  jenkins:
    external: true
  artifactory-data:
    external: true
  artifactory-logs:
    external: true
  artifactory-etc:
    external: true
