version: "2"

services:
  welcomepage:
    build: welcomepage

  jenkins:
    image: jenkins
    #environment:
    #  - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins:/var/jenkins_home

  applauncher:
    build: AppLauncher
    environment:
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_USER=${JENKINS_USER}
      - JENKINS_PASSWORD=${JENKINS_PASSWORD}
      - DOCKER_HUB_USER=${DOCKER_HUB_USER}
      - DOCKER_HUB_PASSWORD=${DOCKER_HUB_PASSWORD}

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    volumes:
      - artifactory:/var/opt/jfrog/artifactory/

  nginx-proxy:
    build: nginx-proxy
    ports:
      - "443:443"

volumes:
  jenkins:
    external: true
  artifactory:
    external: true
