version: "3.1"

services:
  welcomepage:
    build: welcomepage
    logging:
      driver: "gelf"
      options:
        gelf-address: "${LOGSTASH_URL}"

  adminpage:
    build: adminpage
    logging:
      driver: "gelf"
      options:
        gelf-address: "${LOGSTASH_URL}"

  jenkins:
    image: jenkins
    #environment:
    #  - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    logging:
      driver: "gelf"
      options:
        gelf-address: "${LOGSTASH_URL}"

  applauncher:
    build: AppLauncher
    #ports:
    #  - "8090:5000"
    environment:
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_USER=${JENKINS_USER}
      - JENKINS_PASSWORD=${JENKINS_PASSWORD}
      - ARTIFACTORY_URL=${ARTIFACTORY_URL}
      - ARTIFACTORY_USER=${ARTIFACTORY_USER}
      - ARTIFACTORY_PASSWORD=${ARTIFACTORY_PASSWORD}
      - DOCKER_HUB_USER=${DOCKER_HUB_USER}
      - DOCKER_HUB_PASSWORD=${DOCKER_HUB_PASSWORD}
      - STACK_LIST_URL=${STACK_LIST_URL}
    depends_on:
      - jenkins
    logging:
      driver: "gelf"
      options:
        gelf-address: "${LOGSTASH_URL}"

  agilecloudframework:
    build:
      context: AgileCloudFramework
    logging:
      driver: "gelf"
      options:
        gelf-address: "${LOGSTASH_URL}"

  fileserver:
    build:
      context: GithubAdapter
    volumes:
      - ${HOME}/config/GithubAdapter-config.json:/src/config.json
    #logging:
    #  driver: "gelf"
    #  options:
    #    gelf-address: "${LOGSTASH_URL}"

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    volumes:
      - artifactory-data:/var/opt/jfrog/artifactory/data
      - artifactory-logs:/var/opt/jfrog/artifactory/logs
      - artifactory-etc:/var/opt/jfrog/artifactory/etc
    logging:
      driver: "gelf"
      options:
        gelf-address: "${LOGSTASH_URL}"

  nginx-proxy:
    build: nginx-proxy
    ports:
      - "443:443"
    depends_on:
      - jenkins
      - applauncher
      - artifactory
      - welcomepage
      - adminpage
    logging:
      driver: "gelf"
      options:
        gelf-address: "${LOGSTASH_URL}"

volumes:
  jenkins:
    external: true
  artifactory-data:
    external: true
  artifactory-logs:
    external: true
  artifactory-etc:
    external: true
