version: "2"

services:
  welcomepage:
    build: welcomepage

  jenkins:
    image: jenkins

  applauncher:
    build: AppLauncher
    environment:
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_USER=${JENKINS_USER}
      - JENKINS_PASSWORD=${JENKINS_PASSWORD}
      - DOCKER_HUB_USER=${DOCKER_HUB_USER}
      - DOCKER_HUB_PASSWORD=${DOCKER_HUB_PASSWORD}
    ports:
      - "7373:5000"
  nginx-proxy:
    build: nginx-proxy
    ports:
      - 443:443
